config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :words, except: [:show]
  resources :photos, except: [:edit, :update, :show] do
    member do
      post :activate
      post :deactivate
    end
  end
  root 'photos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/usable.rb
module Usable
  extend ActiveSupport::Concern

  included do
    scope :unused, -> do
      n = order(used: :desc).last.used
      unused = where(used: n)
      unused.count > 20 ? unused :  order(used: :asc).limit(20)
    end
  end

  def use!
    self.increment!(:used)
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  # modules
  include Usable

  # fields
  mount_uploader :image, ImageUploader
  serialize :tags, Array
  enum source: %w(manual instagram)
  INSTAGRAM_URL = "https://www.instagram.com/p/"

  # scopes
  scope :active, -> {where(active: true)}

  # validations
  validates :instagram_id, uniqueness: true, allow_blank: true
  validates :fingerprint, uniqueness: true, allow_blank: true
  validates :fingerprint, uniqueness: true, allow_blank: true

  # callbacks
  before_save :process_image
  before_create :set_active

  def deactivate
    update(active: false)
  end

  def activate
    update(active: true)
  end

  def instagram_link
    instagram_code ? "#{INSTAGRAM_URL}#{instagram_code}" : nil
  end

  private

    def process_image
      @rekognition = Aws::Rekognition::Client.new(region: 'us-west-2', credentials: aws_credentials)
      faces = @rekognition.recognize_celebrities(image: {bytes: image.file_object.read}).celebrity_faces
      tags = faces.map(&:name)
      self.tags = tags
      self.fingerprint = calculate_fingerprint
    end

    def set_active
      self.active = (source == 'manual') || tags.include?('Vera Brezhneva')
    end

    def aws_credentials
      @aws_credentials ||= Aws::Credentials.new(Rails.application.secrets.aws[:id], Rails.application.secrets.aws[:secret])
    end

    def calculate_fingerprint
      phashion = Phashion::Image.new(image.file_object.path)
      phashion.fingerprint
    end
end

app/models/word.rb
class Word < ApplicationRecord
  include Usable

  enum kind: [:adj, :fish]

  validates :word, uniqueness: { scope: :kind }
  validates :word, presence: true

  class<< self
    def create_normalized(word, kind)
      kind = kind.to_i
      word = word.chomp.squish
      word = word.mb_chars.downcase
      word = feminize(word) if kind.to_i == 0
      self.find_or_create_by(word:  word, kind: kind)
    end

    def random_text
      fish = self.fish.unused.sample
      adj = self.adj.unused.sample
      fish.use! && adj.use!
      "#{adj.word} #{fish.word}"
    end

    private

    def feminize(word)
      word = word[0..-3] + "яя" if word.ends_with?("ий")
      word = word[0..-3] + "ая" if word.ends_with?("ый")
      word
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  http_basic_authenticate_with Rails.application.secrets.basic_auth
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:destroy, :deactivate, :activate]

  # GET /photos
  def index
    @photos = Photo.order(:used, :updated_at)
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # POST /photos
  def create
    @photo = Photo.new(photo_params)

    if @photo.save
      redirect_to photos_url
    else
      render :new
    end
  end

  # DELETE /photos/1
  def destroy
    @photo.destroy
    redirect_to photos_url, notice: 'Photo was successfully destroyed.'
  end

  def activate
    @photo.activate
    redirect_to photos_url, notice: 'Photo was successfully activated.'
  end

  def deactivate
    @photo.deactivate
    redirect_to photos_url, notice: 'Photo was successfully deactivated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def photo_params
      params.require(:photo).permit(:image)
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:edit, :update, :destroy]

  # GET /words
  def index
    @words = Word.order(:used, :updated_at)
    @words = @words.where(kind: params[:kind]) if params.key?(:kind)
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  def create
    @word = Word.new(word_params)

    if @word.save
      redirect_to words_url, notice: 'Word was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /words/1
  def update
    if @word.update(word_params)
      redirect_to words_url, notice: 'Word was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /words/1
  def destroy
    @word.destroy
    redirect_to words_url, notice: 'Word was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def word_params
      params.require(:word).permit(:word, :kind)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def enum_select(model, enum)
    keys = model.public_send(enum.to_s.pluralize).public_send(:keys)
    keys.map { |k| [t(['enums', enum, k].join('.')), k]}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fishgender</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <%= link_to t('menu.title'), root_url, class: 'navbar-brand' %>
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to t('menu.photos'), photos_path, class: "#{controller_name == 'photos' ? 'nav-link active' : 'nav-link'}"%>
          </li>
          <li class="nav-item">
            <%= link_to t('menu.words'), words_path, class: "#{controller_name == 'words' ? 'nav-link active' : 'nav-link'}"%>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="container pt-2">
      <% if notice %>
        <div id="notice" class="alert alert-primary" role="alert"><%= notice %></div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.file_field :image, class: 'form-control-file' %>
  </div>
  <%= form.submit t('actions.submit'), class: 'btn btn-success' %>
<% end %>

app/views/photos/index.html.erb
<div class="row mt-2">
  <div class="col">
    <%= link_to t('actions.new'), new_photo_path, class: 'btn btn-primary' %>
  </div>
</div>
<div class="row mt-2">
  <% @photos.each do |photo| %>
    <div class="col-4">
       <%= image_tag(photo.image_url, class: 'img-fluid') %>
    </div>
    <div class="col-1">
      <%= photo.tags.join(', ') %>
    </div>
    <div class="col-1">
      <%= photo.used %>
    </div>
    <div class="col-3">
      <% if photo.instagram_code %>
        <%= link_to photo.instagram_link, photo.instagram_link %>
      <% end %>
    </div>
    <div class="col-3">
      <div class="btn-group  btn-group-sm">
        <% if photo.active? %>
          <%= link_to t('actions.deactivate'), deactivate_photo_path(photo), class: 'btn btn-danger', method: :post %>
        <% else %>
          <%= link_to t('actions.activate'), activate_photo_path(photo), class: 'btn btn-success', method: :post %>
        <% end %>
        <%= link_to t('actions.destroy'), photo, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      </div>
    </div>
  <% end %>
</div>

app/views/photos/new.html.erb
<%= form_with(model: @photo, local: true) do |form| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.file_field :image, class: 'form-control-file' %>
  </div>
  <%= form.submit t('actions.submit'), class: 'btn btn-success' %>
<% end %>

app/views/words/_form.html.erb
<%= form_with(model: word, local: true) do |form| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group row">
    <%= form.label :word, class: 'col-2 col-form-label' %>
    <div class="col-10">
      <%= form.text_field :word, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label :kind, class: 'col-2 col-form-label' %>
    <div class="col-10">
      <%= form.select :kind, enum_select(Word, :kind), {}, class: 'form-control' %>
    </div>
  </div>
  <%= form.submit t('actions.submit'), class: 'btn btn-success' %>
<% end %>

app/views/words/edit.html.erb
<%= render 'form', word: @word %>

app/views/words/index.html.erb
<div class="row mt-2 justify-content-between">
  <div class="col-2">
    <%= link_to t('actions.new'), new_word_path, class: 'btn btn-primary' %>
  </div>
  <div class="col-4">
    <div class="btn-group btn-group float-right">
      <%= link_to t('enums.kind.fish'), words_path(kind: :fish), class: 'btn btn-info' %>
      <%= link_to  t('enums.kind.adj'), words_path(kind: :adj), class: 'btn btn-info' %>
      <%= link_to  t('enums.kind.all'), words_path,  class: 'btn btn-info' %>
    </div>
  </div>
</div>
<div class="row mt-2">
  <div class="col">
    <table class="table table-sm table-striped">
      <tbody>
        <% @words.each do |word| %>
          <tr>
            <td><%= word.word %></td>
            <td>
              <%= word.used%>
            </td>
            <td>
              <div class="btn-group btn-group-sm float-right">
                <%= link_to t('actions.edit'), edit_word_path(word), class: 'btn btn-info' %>
                <%= link_to t('actions.destroy'), word, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/words/new.html.erb
<%= render 'form', word: @word %>